###
GET http://localhost:3000/users?username=jonedoe
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWIxMjdjMjIwZTY5MzQxY2U2ZjQ5Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDQxMzExMSwiZXhwIjoxNjk0NDk5NTExfQ.xmGMUADhzqnWqUFMpvLHwZHI4s3dllifbjWIlqyPNvs
###
GET http://localhost:3000/users/64eda30e84f60d5c2d3f3947
Authorization: eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWIxMjdjMjIwZTY5MzQxY2U2ZjQ5Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDQxMzExMSwiZXhwIjoxNjk0NDk5NTExfQ.xmGMUADhzqnWqUFMpvLHwZHI4s3dllifbjWIlqyPNvs

### 
GET http://localhost:3000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWIxMjdjMjIwZTY5MzQxY2U2ZjQ5Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDQxMzExMSwiZXhwIjoxNjk0NDk5NTExfQ.xmGMUADhzqnWqUFMpvLHwZHI4s3dllifbjWIlqyPNvs

###
POST http://localhost:3000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWIxMjdjMjIwZTY5MzQxY2U2ZjQ5Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDQxMzExMSwiZXhwIjoxNjk0NDk5NTExfQ.xmGMUADhzqnWqUFMpvLHwZHI4s3dllifbjWIlqyPNvs
Content-Type: application/json

{
    "first_name": "Jone",
    "last_name": "Doe",
    "age": 23,
    "role": "admin",
    "username": "jonedoe",
    "password": "1234"
}   

###
PATCH http://localhost:3000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWIxMjdjMjIwZTY5MzQxY2U2ZjQ5Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDQxMzExMSwiZXhwIjoxNjk0NDk5NTExfQ.xmGMUADhzqnWqUFMpvLHwZHI4s3dllifbjWIlqyPNvs
Content-Type: application/json

{
    "role": "employee",
    "password": "1234"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "jonedoe",
    "password": "1234"
}